playwright-community/jest-playwright

.github/workflows/nodejs.yml
It looks like, that GitHub Actions needs to be enabled on that repository.
=> ci: added GitHub Actions

README.md, package.json, src/PlaywrightEnvironment.js
I feel really bad about this, that we just mostly copy the code from `jest-puppeteer` there.
Closes #8
=> feat: added debugging functionality

src/PlaywrightEnvironment.js
=> Change priority for configured options

src/PlaywrightEnvironment.js
Should fix https://github.com/mmarkelov/jest-playwright/issues/19#issuecomment-586144626
=> Close browser in teardown

package-lock.json, package.json, src/PlaywrightEnvironment.js
=> Support jest dev server

.eslintignore, .eslintrc.js, .github/workflows/nodejs.yml, package-lock.json, package.json, src/PlaywrightEnvironment.ts, src/bin/index.ts, src/bin/testProcess.ts, src/bin/utils.test.ts, src/bin/utils.ts, src/constants.ts, src/global.ts, src/utils.test.ts, src/utils.ts, types/global.d.ts
=> feat: reworked linting

.github/workflows/nodejs.yml, README.md, package-lock.json, package.json
=> Add coveralls

package-lock.json, package.json
Have to add docs in the README.
Closes #49
=> enh: package.json installation of playwright

package.json
=> fix: added missing typings declaration

src/bin/testProcess.ts, src/bin/utils.test.ts, src/bin/utils.ts, tsconfig.json
=> Add messages for browser test processes

src/PlaywrightEnvironment.ts, src/bin/testProcess.ts, src/constants.ts, src/utils.test.ts, src/utils.ts
#61 
I just got troubles with passing config through `jest.config.js`, I'll try to find out solution
=> Use jest root dir

README.md
=> docs(readme): added jest-dev-server

README.md
Something like that would be useful in my mind. Feel free to add comments regarding spelling or wording.
=> docs: add note about the timeout issue

src/PlaywrightEnvironment.ts
According to #77 
Just rewrite device selection logic
=> Rewrite device selection

.eslintrc.js, .github/workflows/nodejs.yml, .snyk, package-lock.json, package.json, src/PlaywrightEnvironment.ts, src/bin/index.ts, src/bin/testProcess.ts, src/bin/utils.ts, tests/stub.test.ts
=> Update dependencies, migrate to snyk

package-lock.json, package.json
=> Move jest-dev-server to dep

README.md, src/PlaywrightEnvironment.ts, src/constants.ts
Hi,
Please consider adding this 'connect' feature. It would be helpful for our service on https://headlesstesting.com to connect to the browsers in our grid.
Thanks
=> feat: add 'connectBrowserApp' option

src/PlaywrightEnvironment.ts
=> fix: playwright-core import instead of playwright

README.md
=> docs: reference eslint-plugin-jest-playwright

src/utils.test.ts, src/utils.ts
=> Fix selectors registration

README.md, src/PlaywrightEnvironment.ts
Fixes https://github.com/playwright-community/jest-playwright/issues/107. Seems like it was added but never actually hooked up.
=> fix: wire up exitOnPageError config option

e2e/stub.test.ts, src/PlaywrightEnvironment.ts, types/global.d.ts
Added the ability to access the browser and device in a current test.
Closes #110
=> feat: ability of access current device and browser inside test

README.md
They didn't point to the new organization 'Playwright Community'.
Also did some minor spelling corrections.
=> docs: Update README.md links for util packages

package-lock.json, package.json, src/PlaywrightRunner.ts, src/constants.ts, src/global.ts
=> Fix rootDir for tests

.eslintrc.js, src/PlaywrightEnvironment.ts, src/PlaywrightRunner.ts, src/types.ts, src/utils.test.ts, src/utils.ts
Not sure if it works, I have not tested it. Do you have a test setup locally running? Otherwise I can test it.
Let me know what you think.
=> fix: refactored device loading

src/PlaywrightRunner.ts
=> Fix devices check in PlaywrightRunner

src/PlaywrightRunner.ts
Will fix https://github.com/microsoft/playwright/issues/2343#issuecomment-633373607
=> Replace flatMap for PlaywrightRunner

README.md
=> docs: add information about available globals

README.md
Closes #149
Not sure where to put
=> docs: added separate Jest config in README

README.md, src/PlaywrightEnvironment.ts, types/global.d.ts
=> Add resetPage and resetBrowser

src/PlaywrightEnvironment.ts, src/PlaywrightRunner.ts, src/constants.ts, src/types.d.ts
=> Allow configure launch browser type

.github/workflows/nodejs.yml
Relates to that issue: https://github.com/playwright-community/playwright-jest-examples/issues/12#issuecomment-658700666
=> ci: test also on latest Node.js version

src/PlaywrightEnvironment.ts
Fixes #250
Basically the same implementation as in upstream Playwright, just a bit generic with the `toString()` method.
https://github.com/microsoft/playwright/blob/e5afd927623debe7f6de9816cc85ad913f29d7b0/test/utils.js#L98-L106
=> fix: selector will be register multiple times

README.md
Let me know if we can formulate it better. Request came from a direct user feedback that it was not clear for him.
=> docs: clarify a new context per each test file

src/PlaywrightEnvironment.ts, types/global.d.ts
Close #343 
I just put it in `try-catch` block, cause I need we should support earlier versions of `playwright`
=> Fix page close

src/PlaywrightRunner.ts
=> Using passed wsEndpoint

README.md
=> Add testEnvironmentOptions option to docs

src/utils.ts
I think that we can remove it for the next release
=> Remove check validation options

README.md
=> Add information about shadow dom selectors

README.md, e2e/more.test.ts, src/PlaywrightEnvironment.ts, src/PlaywrightRunner.ts, src/extends.ts, src/utils.test.ts, src/utils.ts, types/global.d.ts
=> Fix debug functions

README.md
Fix broken links on README docs.
=> Fix broken links on README doc

types/global.d.ts
https://github.com/playwright-community/jest-playwright/issues/499#issuecomment-779257789
=> Fix serverOptions type

src/utils.test.ts, src/utils.ts
=> Fix unnecessary mutation of options

src/PlaywrightEnvironment.ts, src/PlaywrightRunner.ts, src/utils.test.ts, src/utils.ts
=> Change logic of useDefaultBrowserType

src/PlaywrightEnvironment.ts
=> Fix reset helper functions

package-lock.json, package.json, src/PlaywrightRunner.ts, src/coverage.ts
=> Bump expect-playwright

src/utils.test.ts, src/utils.ts
=> Add ability to use function in config

.github/workflows/nodejs.yml, package-lock.json, package.json
Going to publish a new version after this change.
=> chore: bump dependencies
