package.json
src/PlaywrightEnvironment.js
src/constants.js
src/global.js

This patch launches browser per-worker. This is generally
a workaround for WebKit lacking multi-client support: https://github.com/microsoft/playwright/issues/830
Fixes #5

feat: create browser per-worker

---

src/utils.js

Currently we have to provide the `webSocket: true` value manually if we are using a custom `launchBrowserApp` setting.
With this change the `launchBrowserApp` and `config` option will inherit from the default config, so that we don't have to specify it.

feat: inherit from default config on objects

---

README.md
package-lock.json
package.json
src/PlaywrightEnvironment.js
src/utils.js
src/utils.test.js

I just think about support this feature, but I haven't got any ideas about clean and simple API.
In this PR my thoughts about it. You can add come configuration to support specific version through `jest-playwright.config.js` :
```javascript
module.exports = {
browser: 'firefox',
useStandaloneVersion: true,
...
}
```
or with env params: `BROWSER=firefox USE_STANDALONE_VERSION=true jest` 
Also I should think about **peerDependencies**, should it be replaced with **optionalDependencies**?
#7

Ability to support specific browser

---

README.md

Add --save-dev to npm instruction.
Add jest as install dependency.
Move usage instruction under single header "Usage".
Clarify browser type note.

Add clarifying statements to readme

---

package-lock.json
src/PlaywrightEnvironment.js
src/utils.js
src/utils.test.js

Add ability to set device with env variable, like so:
```
BROWSER=chromium DEVICE='Nexus 4' jest
```
This is the step to support running tests for multiple devices:
https://github.com/mmarkelov/jest-playwright/issues/19

Add ability to support device from env

---

package-lock.json
package.json
src/utils.js

- fix: that the standalone exports are now the same like the normal `playwright` package (https://github.com/microsoft/playwright/pull/818)
- fix: dependencies should not be in `optionalDependencies` and `devDependencies` at the same time. NPM logged for that a warning. So I've adjusted it. But not 100% sure if it's correct like that. Providing versions for them is in my mind a good idea.
```
npm WARN The package jest-dev-server is included as both a dev and production dependency.
npm WARN The package playwright is included as both a dev and production dependency.
```
Closes #33 
(It wasn't working with the 0.11+ version when the standalone version was used.)
```
TypeError: playwrightInstance.launch is not a function
```

fix: Playwright 0.11.0+ support

---

src/bin/testProcess.ts

An idea how to implement it. What do you think @mmarkelov?
Closes #55

feat: set correct process exit code

---

README.md
src/bin/testProcess.ts
src/bin/utils.test.ts
src/bin/utils.ts
src/constants.ts
src/utils.ts

https://github.com/mmarkelov/jest-playwright/issues/19#issuecomment-584937549

Running multiple devices

---

src/PlaywrightEnvironment.ts
src/constants.ts
src/utils.ts

#60 
I decided that move something to **global**  isn't really good solution. So I decide to move this logic inside. So you can config selectors with `jest-playwright.config.js`:
```js
const {
selectorEngine,
} = require('query-selector-shadow-dom/plugins/playwright');
module.exports = {
selectors: [
{engine: selectorEngine, name: 'shadow'}
],
...
}
```
You can specify it with array of object with **engine** and **name**. So **jest-playwright** will iterate through it and will register whole array

Add ability to config selectors

---

src/PlaywrightEnvironment.ts
src/bin/testProcess.ts
src/bin/utils.test.ts
src/bin/utils.ts

Just made some improvements to display some info about environment:

Improve logs for jest-playwright command

---

src/bin/testProcess.ts
types/global.d.ts

Actually I didn't know the best way for this case. May be we should warn user that he try to run tests in parallel for only one. For now I just decided to run tests for only one browser, but I'm not sure that is right approach

Fixes to check browsers

---

.github/workflows/nodejs.yml
README.md
package-lock.json
package.json
src/PlaywrightEnvironment.ts
src/bin/testProcess.ts
src/constants.ts
src/utils.test.ts
src/utils.ts

Changes:
- Fix that GitHub Actions ran multiple times for a incoming Pull Request
- Enabled TypeScript checking in the CI step
- Added Requirements section to the README
- Dropped support for using the Playwright instance via `playwright-core` since they dropped the `downloadBrowserIfNeeded` method
Closes #86

feat: support for Playwright version 0.12

---

README.md

Was not documented yet and tracked internally in #41.
Maybe it also solves the issue #4 but not fully sure, was not into context.

docs: add usage with TypeScript

---

README.md
jest-preset.json
package-lock.json
package.json

feat: added expect-playwright

---

src/PlaywrightEnvironment.ts
src/PlaywrightRunner.ts

Using **jest-circus** to set timeouts underhood. This is another kind of hacky solution. I'm not sure about setting it inside **handleTestEvent** for `jestPlaywright.debug`, cause check whole tests have this function can be slow. But I suppose increasing it inside runner can be a good idea

Set timeouts underhood

---

src/PlaywrightEnvironment.ts
src/global.ts

Move jest-dev-server to global

---

.eslintrc.js
src/PlaywrightEnvironment.ts
src/PlaywrightRunner.ts
src/types.ts
src/utils.test.ts
src/utils.ts

Close #125 
I'm not sure if it's really nice solution, cause it's make TS unhappy. Some research on it.
With current **playwright** version there is `index.js` file in **playwright-core** package
But with **next** version it’s missed
@mxschmitt maybe you got some information about it. Cause maybe it's a bug.

Fix devices error with playwright-core

---

src/PlaywrightEnvironment.ts
src/utils.test.ts
src/utils.ts

In the previous release there was a bug, that caused `checkDependenices()` to return an empty object if no playwright package was found. This resulted to a truthy if condition here:
https://github.com/playwright-community/jest-playwright/blob/6e0d933c92db88b59e2ba4f6d16f09a4e7dca348/src/utils.ts#L78-L95
Which cause the following error:
```
None of playwright packages was not found in dependencies
```

fix: checkDependencies if no package was found

---

README.md
src/PlaywrightEnvironment.ts
src/PlaywrightRunner.ts
src/constants.ts
src/global.ts
src/types.d.ts
src/utils.test.ts
src/utils.ts

Definitely something which we should mention with bold text in the change log. Also thought about adding it to the code like that: if the old options are set, then throw an error message. We could also use something like that: https://www.npmjs.com/package/jest-validate

breaking: standardise options

---

README.md
src/constants.ts
src/utils.ts

As discussed in #146
jest-validate is not a good for us, since we use quite a lot of data structures like context/connect/launch options which are not that well known, thats why I implemented a solution for that myself.

feat: log option key renamings to console

---

.eslintrc.js
README.md
package-lock.json
package.json
src/PlaywrightEnvironment.ts
src/PlaywrightRunner.ts
src/constants.ts
src/coverage.ts
src/types.d.ts
src/utils.ts
types/global.d.ts

TODOs:
Example usage here: https://github.com/playwright-community/playwright-jest-examples/pull/8
Will look like that if you are using the example:

feat: collect coverage of end-to-end tests

---

src/PlaywrightEnvironment.ts
src/PlaywrightRunner.ts
src/types.d.ts
src/utils.test.ts
src/utils.ts

Allow configure browser specific options

---

.github/workflows/nodejs.yml
.gitignore
e2e/more.test.ts
e2e/stub.test.ts
jest-playwright.config.js
jest.config.e2e.js
src/PlaywrightEnvironment.ts
src/types.d.ts
src/utils.test.ts
src/utils.ts
types/global.d.ts

close #174 
It will be able through `jestPlaywright` object:
```js
// You can pass browser and device by the first argument
jestPlaywright.skip({ browser: 'chromium' }, () => {
// it will be able to use `describe` or `it`
test('should display "google" text on page', async () => {
const title = await page.title()
expect(title).toBe('Google')
})
test('test 2', () => {
expect(1).toBe(1)
})
})
```

Allow skip test ability

---

README.md
src/PlaywrightRunner.ts
src/types.d.ts
src/utils.test.ts
src/utils.ts

Just think that the using of **RegExp** will be helpful to define devices.
```js
// jest-playwright.config.js
module.exports = {
...
devices: /iPhone 8/
}
```
Will run tests for **iPhone 8**, **iPhone 8 landscape**, **iPhone 8 Plus** and **iPhone 8 Plus landscape**.
Also it will be able for skip test.

Add ability to use RegExp pattern to define devices

---

README.md
package-lock.json
package.json
src/PlaywrightEnvironment.ts
src/constants.ts
src/types.d.ts

close #191 #194 and perhaps #144

Docs fixes

---

types/global.d.ts

close #205 
@mxschmitt I don't have a nice way to do it. But seems like we can't include **types** from the **src** directory, cause we will need also include **constants**, cause internal types use them.

Fix global types

---

package-lock.json
package.json
src/PlaywrightEnvironment.ts
types/global.d.ts

close #212 
Also added same opportunity for `resetBrowser`

Add params to resetContext

---

src/utils.test.ts
src/utils.ts

Add ability to check cjs config

---

README.md
e2e/more.test.ts
src/types.d.ts
src/utils.test.ts
src/utils.ts
types/global.d.ts

coming from https://github.com/playwright-community/jest-playwright/issues/174#issuecomment-657850012
I suppose that `jestPlaywright.skip` method should take options like `jest-playwright.config` to be consistence.
**Before:** 
```js
jestPlaywright.skip({ browser: 'chromium', device: 'Pixel 2' }, () => {
test('should skip this one', async () => {
const title = await page.title()
expect(title).toBe('Google')
})
test('and this one', () => {
expect(1).toBe(2)
})
})
```
**After:**
```js
jestPlaywright.skip({ browsers: ['chromium'], devices: ['Pixel 2'] }, () => {
test('should skip this one', async () => {
const title = await page.title()
expect(title).toBe('Google')
})
test('and this one', () => {
expect(1).toBe(2)
})
})
```

jestPlaywright skip improvements

---

types/global.d.ts

Import types was added only in **3.8**.
I suppose we should remove it to support earlier versions. Originally came from https://github.com/playwright-community/jest-playwright/issues/181

Fix ts global declaration

---

extends.js
jest-preset.json
package-lock.json
src/PlaywrightEnvironment.ts
src/types.d.ts

#216 
Seems to be a bit challenging to implement this in a nice way. IDK if it will be helpful to configure **playwright** for just one test. The only founded solution was to use isolation playwright configuration.
It will be smth like that:
```js
describe('Simple tests',  () => {
beforeAll(async () => {
await page.goto('https://google.com/')
})
test('test1', async () => {
await jestPlaywright.config({
browser: 'chromium',
launchType: "LAUNCH",
launchOptions: {
headless: false,
devtools: true,
}
}, async ({page}) => {
// page is coming from function params
await page.goto('https://github.com/')
const title = await page.title()
expect(title).toBe('Google')
})
})
test('test2', async () => {
const title = await page.title()
expect(title).toBe('Google')
})
afterAll(async () => {
await …
```

Add ability to configure playwright in test file

---

e2e/more.test.ts
extends.js
jest.config.e2e.js
src/PlaywrightEnvironment.ts
types/global.d.ts

Replaced current logic:
```js
jestPlaywright.skip({ browsers: ['chromium'] }, () => {
test('should skip this one', async () => {
const title = await page.title()
expect(title).toBe('Google')
})
})
```
with
```js
it.jestPlaywrightSkip({ browsers: ['chromium'] }, 'should skip this one', async () => {
const title = await page.title()
expect(title).toBe('Google')
})
```

Change jestPlaywright skip API

---

extends.js
src/PlaywrightEnvironment.ts

Some improvements to debug helpers:
```js
// DEBUG uses `debugOptions` config
test.jestPlaywrightDebug('test1', async () => {
// ...
});
// DEBUG with configuration object merges options with `debugOptions` config
test.jestPlaywrightDebug({ /* ... */ }, 'test2', async () => {
// ...
});
// CONFIG must pass a configuration object and merges passed options with primary config
test.jestPlaywrightConfig({ /* ... */ }, 'test3', async () => {
// ...
});
```

jestPlaywright debug improvements

---

extends.js
src/PlaywrightEnvironment.ts
src/utils.ts
types/global.d.ts

Added ability to use `skip` and `only` for custom `jestPlaywright` functions:
```js
// Run specific test(s) only
test.jestPlaywrightDebug.only('test1', async () => {
// ...
});
// Skip specific test(s)
test.jestPlaywrightConfig.skip({ /* ... */ }, 'test2', async () => {
// ...
});
```
https://github.com/playwright-community/jest-playwright/issues/216#issuecomment-663236709

jestPlaywright helpers skip and only

---

src/PlaywrightEnvironment.ts
types/global.d.ts

Added ability to support `debugOptions` in `jest-playwright.config`
```js
// jest-playwright.config.js
module.exports = {
browsers: ['chromium', 'firefox', 'webkit'],
debugOptions: {
browsers: ['chromium'],
launchOptions: {
headless: false,
},
},
};
```
Extra information in #216 comments

Add ability to config debugOptions with jest-playwright.config

---

src/PlaywrightEnvironment.ts
src/PlaywrightRunner.ts
src/constants.ts
src/global.ts
src/utils.test.ts
src/utils.ts

https://github.com/playwright-community/jest-playwright/issues/226#issuecomment-661825110
Added ability to pass config with **jest.config.js**:
```js
testEnvironmentOptions: {
...,
'jest-playwright': {
...
}
},
```
Also find out that there is problem with **globalSetup**, it will try to use config from root directory. IDK how we can use actual configuration, cause we got only **globalConfig** there

Add ability to pass config with jest config

---

src/PlaywrightEnvironment.ts

Fixes #337
In the Playwright-CLI we do it in the same way.

fix(firefox): remove isMobile in Firefox

---

e2e/more.test.ts
types/global.d.ts

in https://github.com/playwright-community/jest-playwright/blob/master/src/extends.ts#L104 `describe` is extended with `jestPlaywrightSkip` but when I tried to use it typescript was complaining that it doesn't exist. 
This will add the type in just like the `it`.

Extend Describe to include jestPlaywrightSkip

---

README.md

The docs had it backwards, `jestPlaywrightDebug` disables headless mode rather than turning it on.

Fix `jestPlaywrightDebug` docs re: `headless` mode

---

README.md

I found that some links in the README are outdated. This PR fixes those links. To prevent further issue, I also replace `master` in links to a special tag.

Fix links in the documents

---

src/PlaywrightRunner.ts

This one-line PR will make the users have the ability to set jest `displayName.color`.

Added ability to set displayName.color

---

src/global.ts

In [#146](https://github.com/playwright-community/jest-playwright/pull/146/files#diff-0bec2401f35d4c80319a0256eadb80621ce9a826423909629bb0708b7758307dR37), `server` in the config was renamed to `serverOptions`. However, the error message wasn't updated.
This PR corrects the error message.

Corrected some error messages

---

package-lock.json
package.json

It is used in `src/PlaywrightRunner.ts`, but it was not a direct dependency. This fixes a compatibility issue with yarn pnp.

Adds jest-runner as dependency

---

src/PlaywrightRunner.ts

There are two issue.
1. always launches the server when skipInitialization is not defined even though we pass `launchType: SERVER` and  `wsEndpoint`.
https://github.com/playwright-community/jest-playwright/blob/06737bd4d311555f5d0fb2cdb87540e46b101e68/src/PlaywrightRunner.ts#L122
2. wsEndpoint can be defined in each client, but the logic is not applied it
https://github.com/playwright-community/jest-playwright/blob/06737bd4d311555f5d0fb2cdb87540e46b101e68/src/PlaywrightRunner.ts#L148
As a result, we couldn't use `wsEndpoint` to connect the existing browser.

fix connectOptions issue

---

README.md

As mentioned in [that project's README](https://github.com/Georgegriff/query-selector-shadow-dom#playwright):
> Update: as of Playwright v0.14.0 their CSS and text selectors work with shadow Dom out of the box, **you don't need this library anymore for Playwright**.

Remove outdated section about query-selector-shadow-dom

---

README.md
src/PlaywrightEnvironment.ts
src/utils.test.ts
src/utils.ts

Deprecate setting browser and device with env

---

package-lock.json
src/PlaywrightEnvironment.ts
src/coverage.ts
src/utils.ts
types/global.d.ts

Make collect coverage optional

---

src/PlaywrightRunner.ts
src/utils.test.ts
src/utils.ts

Make new identificator for browser2server

---

README.md
src/PlaywrightEnvironment.ts
src/PlaywrightRunner.ts
src/constants.ts

Increase jest timeout for PWDEBUG option

---

README.md
src/PlaywrightEnvironment.ts

Remove jestPlaywright debug

---

README.md

It will close this one: https://github.com/playwright-community/jest-playwright/issues/611

document globalSetup and globalTeardown

---

src/extends.ts

https://github.com/playwright-community/jest-playwright/discussions/672

Add ability to pass timers to jestPlaywright tests

---

types/global.d.ts

Declare module

---

package-lock.json
package.json
types/global.d.ts

Fix jest types

---

README.md
src/extends.ts
types/global.d.ts

close #660 
will be controlled by `resetContextPerTest` in config. (**false** as default for a now)

Add ability to reset context per test

---

package-lock.json
package.json
types/global.d.ts

Fixes #794
I did it in a separate PR since more changes were required to make CI green.

chore: lock jest peer dependency to version 26 or 27

---

package-lock.json
package.json

Found that a typo had sneeked into the peerDeps.
jest-runner should be at ^29.3.1 like all the other jest peerDeps and not ^29.3.**10**

Fix jest-runner peerDeps
